/*
* generated by Xtext
*/
package nl.sison.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import nl.sison.services.XplatformGrammarAccess;

public class XplatformParser extends AbstractContentAssistParser {
	
	@Inject
	private XplatformGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected nl.sison.ui.contentassist.antlr.internal.InternalXplatformParser createParser() {
		nl.sison.ui.contentassist.antlr.internal.InternalXplatformParser result = new nl.sison.ui.contentassist.antlr.internal.InternalXplatformParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getXplatformHeaderKeyValuePairAccess().getAlternatives_2(), "rule__XplatformHeaderKeyValuePair__Alternatives_2");
					put(grammarAccess.getXplatformJsonAccess().getAlternatives(), "rule__XplatformJson__Alternatives");
					put(grammarAccess.getJsonMetaScalarTypeAccess().getAlternatives(), "rule__JsonMetaScalarType__Alternatives");
					put(grammarAccess.getJsonMetaTypeAccess().getAlternatives(), "rule__JsonMetaType__Alternatives");
					put(grammarAccess.getJsonTypeAccess().getAlternatives(), "rule__JsonType__Alternatives");
					put(grammarAccess.getJsonScalarTypeAccess().getAlternatives(), "rule__JsonScalarType__Alternatives");
					put(grammarAccess.getJsonArrayAccess().getAlternatives(), "rule__JsonArray__Alternatives");
					put(grammarAccess.getXplatformAccess().getGroup(), "rule__Xplatform__Group__0");
					put(grammarAccess.getXplatformAccess().getGroup_6(), "rule__Xplatform__Group_6__0");
					put(grammarAccess.getXplatformAccess().getGroup_6_5(), "rule__Xplatform__Group_6_5__0");
					put(grammarAccess.getXplatformAccess().getGroup_7(), "rule__Xplatform__Group_7__0");
					put(grammarAccess.getXplatformAccess().getGroup_7_3(), "rule__Xplatform__Group_7_3__0");
					put(grammarAccess.getURIAccess().getGroup(), "rule__URI__Group__0");
					put(grammarAccess.getURIAccess().getGroup_1(), "rule__URI__Group_1__0");
					put(grammarAccess.getXplatformHeaderAccess().getGroup(), "rule__XplatformHeader__Group__0");
					put(grammarAccess.getXplatformHeaderAccess().getGroup_3(), "rule__XplatformHeader__Group_3__0");
					put(grammarAccess.getXplatformHeaderKeyValuePairAccess().getGroup(), "rule__XplatformHeaderKeyValuePair__Group__0");
					put(grammarAccess.getXplatformJsonAccess().getGroup_0(), "rule__XplatformJson__Group_0__0");
					put(grammarAccess.getXplatformJsonAccess().getGroup_2(), "rule__XplatformJson__Group_2__0");
					put(grammarAccess.getJsonMetaArrayAccess().getGroup(), "rule__JsonMetaArray__Group__0");
					put(grammarAccess.getJsonScalarTypeAccess().getGroup_2(), "rule__JsonScalarType__Group_2__0");
					put(grammarAccess.getJsonScalarTypeAccess().getGroup_2_1(), "rule__JsonScalarType__Group_2_1__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_0(), "rule__JsonArray__Group_0__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_0_2(), "rule__JsonArray__Group_0_2__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_1(), "rule__JsonArray__Group_1__0");
					put(grammarAccess.getJsonArrayAccess().getGroup_1_2(), "rule__JsonArray__Group_1_2__0");
					put(grammarAccess.getJsonObjectAccess().getGroup(), "rule__JsonObject__Group__0");
					put(grammarAccess.getJsonObjectAccess().getGroup_1(), "rule__JsonObject__Group_1__0");
					put(grammarAccess.getJsonObjectAccess().getGroup_2(), "rule__JsonObject__Group_2__0");
					put(grammarAccess.getXplatformAccess().getNameAssignment_1(), "rule__Xplatform__NameAssignment_1");
					put(grammarAccess.getXplatformAccess().getMethodAssignment_3(), "rule__Xplatform__MethodAssignment_3");
					put(grammarAccess.getXplatformAccess().getUriAssignment_5(), "rule__Xplatform__UriAssignment_5");
					put(grammarAccess.getXplatformAccess().getRequestHeadersAssignment_6_4(), "rule__Xplatform__RequestHeadersAssignment_6_4");
					put(grammarAccess.getXplatformAccess().getResponseHeadersAssignment_6_5_2(), "rule__Xplatform__ResponseHeadersAssignment_6_5_2");
					put(grammarAccess.getXplatformAccess().getJsonToClientAssignment_7_2(), "rule__Xplatform__JsonToClientAssignment_7_2");
					put(grammarAccess.getXplatformAccess().getJsonToServerAssignment_7_3_2(), "rule__Xplatform__JsonToServerAssignment_7_3_2");
					put(grammarAccess.getURIAccess().getUriParameterAssignment_1_1(), "rule__URI__UriParameterAssignment_1_1");
					put(grammarAccess.getXplatformHeaderAccess().getHeaderKeyValuesAssignment_2(), "rule__XplatformHeader__HeaderKeyValuesAssignment_2");
					put(grammarAccess.getXplatformHeaderAccess().getHeaderKeyValuesAssignment_3_1(), "rule__XplatformHeader__HeaderKeyValuesAssignment_3_1");
					put(grammarAccess.getXplatformHeaderKeyValuePairAccess().getKeyAssignment_0(), "rule__XplatformHeaderKeyValuePair__KeyAssignment_0");
					put(grammarAccess.getXplatformHeaderKeyValuePairAccess().getValueAssignment_2_0(), "rule__XplatformHeaderKeyValuePair__ValueAssignment_2_0");
					put(grammarAccess.getXplatformHeaderKeyValuePairAccess().getValueAssignment_2_1(), "rule__XplatformHeaderKeyValuePair__ValueAssignment_2_1");
					put(grammarAccess.getXplatformJsonAccess().getTypeAssignment_0_1(), "rule__XplatformJson__TypeAssignment_0_1");
					put(grammarAccess.getXplatformJsonAccess().getMetaTypeAssignment_1(), "rule__XplatformJson__MetaTypeAssignment_1");
					put(grammarAccess.getXplatformJsonAccess().getCompositeAssignment_2_0(), "rule__XplatformJson__CompositeAssignment_2_0");
					put(grammarAccess.getJsonMetaArrayAccess().getMetaTypeAssignment_1(), "rule__JsonMetaArray__MetaTypeAssignment_1");
					put(grammarAccess.getJsonMetaTypeAccess().getScalarAssignment_0(), "rule__JsonMetaType__ScalarAssignment_0");
					put(grammarAccess.getJsonMetaTypeAccess().getCompositeAssignment_1(), "rule__JsonMetaType__CompositeAssignment_1");
					put(grammarAccess.getJsonCompositeTypeAccess().getCompositeAssignment(), "rule__JsonCompositeType__CompositeAssignment");
					put(grammarAccess.getJsonTypeAccess().getScalarAssignment_0(), "rule__JsonType__ScalarAssignment_0");
					put(grammarAccess.getJsonTypeAccess().getCompositeAssignment_1(), "rule__JsonType__CompositeAssignment_1");
					put(grammarAccess.getJsonScalarTypeAccess().getBoolAssignment_0(), "rule__JsonScalarType__BoolAssignment_0");
					put(grammarAccess.getJsonScalarTypeAccess().getStringAssignment_1(), "rule__JsonScalarType__StringAssignment_1");
					put(grammarAccess.getJsonScalarTypeAccess().getNumberAssignment_2_0(), "rule__JsonScalarType__NumberAssignment_2_0");
					put(grammarAccess.getJsonScalarTypeAccess().getNullAssignment_3(), "rule__JsonScalarType__NullAssignment_3");
					put(grammarAccess.getJsonArrayAccess().getElementsAssignment_0_1(), "rule__JsonArray__ElementsAssignment_0_1");
					put(grammarAccess.getJsonArrayAccess().getElementsAssignment_0_2_1(), "rule__JsonArray__ElementsAssignment_0_2_1");
					put(grammarAccess.getJsonArrayAccess().getCompositesAssignment_1_1(), "rule__JsonArray__CompositesAssignment_1_1");
					put(grammarAccess.getJsonArrayAccess().getCompositesAssignment_1_2_1(), "rule__JsonArray__CompositesAssignment_1_2_1");
					put(grammarAccess.getJsonObjectAccess().getKeysAssignment_1_0(), "rule__JsonObject__KeysAssignment_1_0");
					put(grammarAccess.getJsonObjectAccess().getValuesAssignment_1_2(), "rule__JsonObject__ValuesAssignment_1_2");
					put(grammarAccess.getJsonObjectAccess().getKeysAssignment_2_1(), "rule__JsonObject__KeysAssignment_2_1");
					put(grammarAccess.getJsonObjectAccess().getValuesAssignment_2_3(), "rule__JsonObject__ValuesAssignment_2_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			nl.sison.ui.contentassist.antlr.internal.InternalXplatformParser typedParser = (nl.sison.ui.contentassist.antlr.internal.InternalXplatformParser) parser;
			typedParser.entryRuleXplatform();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public XplatformGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XplatformGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
