/*
 * generated by Xtext
 */
package nl.sison.dsl.mobgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ResourceUiModule extends nl.sison.dsl.mobgen.ui.AbstractResourceUiModule {
	public ResourceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
