/*
* generated by Xtext
*/
package nl.sison.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class XplatformGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class XplatformElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Xplatform");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cResourcesAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cResourcesXplatformResourceDefinitionParserRuleCall_0_0 = (RuleCall)cResourcesAssignment_0.eContents().get(0);
		private final Assignment cCallsAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCallsXplatformCallDefinitionParserRuleCall_1_0 = (RuleCall)cCallsAssignment_1.eContents().get(0);
		
		/// **
		// * 
		// * Xplatform http call generator parser
		// * 
		// * / Xplatform:
		//	(resources+=XplatformResourceDefinition | calls+=XplatformCallDefinition)+;
		public ParserRule getRule() { return rule; }

		//(resources+=XplatformResourceDefinition | calls+=XplatformCallDefinition)+
		public Alternatives getAlternatives() { return cAlternatives; }

		//resources+=XplatformResourceDefinition
		public Assignment getResourcesAssignment_0() { return cResourcesAssignment_0; }

		//XplatformResourceDefinition
		public RuleCall getResourcesXplatformResourceDefinitionParserRuleCall_0_0() { return cResourcesXplatformResourceDefinitionParserRuleCall_0_0; }

		//calls+=XplatformCallDefinition
		public Assignment getCallsAssignment_1() { return cCallsAssignment_1; }

		//XplatformCallDefinition
		public RuleCall getCallsXplatformCallDefinitionParserRuleCall_1_0() { return cCallsXplatformCallDefinitionParserRuleCall_1_0; }
	}

	public class XplatformCallDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XplatformCallDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMethodAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMethodRESTFUL_METHODSTerminalRuleCall_3_0 = (RuleCall)cMethodAssignment_3.eContents().get(0);
		private final Keyword cFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUriAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUriURIParserRuleCall_5_0 = (RuleCall)cUriAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWithKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cHeadersKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cFromKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Keyword cRequestKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Assignment cRequestHeadersAssignment_6_4 = (Assignment)cGroup_6.eContents().get(4);
		private final RuleCall cRequestHeadersXplatformHeaderParserRuleCall_6_4_0 = (RuleCall)cRequestHeadersAssignment_6_4.eContents().get(0);
		private final Group cGroup_6_5 = (Group)cGroup_6.eContents().get(5);
		private final Keyword cAndKeyword_6_5_0 = (Keyword)cGroup_6_5.eContents().get(0);
		private final Keyword cResponseKeyword_6_5_1 = (Keyword)cGroup_6_5.eContents().get(1);
		private final Assignment cResponseHeadersAssignment_6_5_2 = (Assignment)cGroup_6_5.eContents().get(2);
		private final RuleCall cResponseHeadersXplatformHeaderParserRuleCall_6_5_2_0 = (RuleCall)cResponseHeadersAssignment_6_5_2.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cClientKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cExpectsKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cJsonToClientAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cJsonToClientXplatformJsonParserRuleCall_7_2_0 = (RuleCall)cJsonToClientAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cServerKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Keyword cExpectsKeyword_7_3_1 = (Keyword)cGroup_7_3.eContents().get(1);
		private final Assignment cJsonToServerAssignment_7_3_2 = (Assignment)cGroup_7_3.eContents().get(2);
		private final RuleCall cJsonToServerXplatformJsonParserRuleCall_7_3_2_0 = (RuleCall)cJsonToServerAssignment_7_3_2.eContents().get(0);
		
		//XplatformCallDefinition:
		//	"call" name=ID ":" method=RESTFUL_METHODS "from" uri=URI ("with" "headers" "from" "request"
		//	requestHeaders=XplatformHeader ("and" "response" responseHeaders=XplatformHeader)?)? ("client" "expects"
		//	jsonToClient=XplatformJson ("server" "expects" jsonToServer=XplatformJson)?)?;
		public ParserRule getRule() { return rule; }

		//"call" name=ID ":" method=RESTFUL_METHODS "from" uri=URI ("with" "headers" "from" "request"
		//requestHeaders=XplatformHeader ("and" "response" responseHeaders=XplatformHeader)?)? ("client" "expects"
		//jsonToClient=XplatformJson ("server" "expects" jsonToServer=XplatformJson)?)?
		public Group getGroup() { return cGroup; }

		//"call"
		public Keyword getCallKeyword_0() { return cCallKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//method=RESTFUL_METHODS
		public Assignment getMethodAssignment_3() { return cMethodAssignment_3; }

		//RESTFUL_METHODS
		public RuleCall getMethodRESTFUL_METHODSTerminalRuleCall_3_0() { return cMethodRESTFUL_METHODSTerminalRuleCall_3_0; }

		//"from"
		public Keyword getFromKeyword_4() { return cFromKeyword_4; }

		//uri=URI
		public Assignment getUriAssignment_5() { return cUriAssignment_5; }

		//URI
		public RuleCall getUriURIParserRuleCall_5_0() { return cUriURIParserRuleCall_5_0; }

		//("with" "headers" "from" "request" requestHeaders=XplatformHeader ("and" "response" responseHeaders=XplatformHeader)?)?
		public Group getGroup_6() { return cGroup_6; }

		//"with"
		public Keyword getWithKeyword_6_0() { return cWithKeyword_6_0; }

		//"headers"
		public Keyword getHeadersKeyword_6_1() { return cHeadersKeyword_6_1; }

		//"from"
		public Keyword getFromKeyword_6_2() { return cFromKeyword_6_2; }

		//"request"
		public Keyword getRequestKeyword_6_3() { return cRequestKeyword_6_3; }

		//requestHeaders=XplatformHeader
		public Assignment getRequestHeadersAssignment_6_4() { return cRequestHeadersAssignment_6_4; }

		//XplatformHeader
		public RuleCall getRequestHeadersXplatformHeaderParserRuleCall_6_4_0() { return cRequestHeadersXplatformHeaderParserRuleCall_6_4_0; }

		//("and" "response" responseHeaders=XplatformHeader)?
		public Group getGroup_6_5() { return cGroup_6_5; }

		//"and"
		public Keyword getAndKeyword_6_5_0() { return cAndKeyword_6_5_0; }

		//"response"
		public Keyword getResponseKeyword_6_5_1() { return cResponseKeyword_6_5_1; }

		//responseHeaders=XplatformHeader
		public Assignment getResponseHeadersAssignment_6_5_2() { return cResponseHeadersAssignment_6_5_2; }

		//XplatformHeader
		public RuleCall getResponseHeadersXplatformHeaderParserRuleCall_6_5_2_0() { return cResponseHeadersXplatformHeaderParserRuleCall_6_5_2_0; }

		//("client" "expects" jsonToClient=XplatformJson ("server" "expects" jsonToServer=XplatformJson)?)?
		public Group getGroup_7() { return cGroup_7; }

		//"client"
		public Keyword getClientKeyword_7_0() { return cClientKeyword_7_0; }

		//"expects"
		public Keyword getExpectsKeyword_7_1() { return cExpectsKeyword_7_1; }

		//jsonToClient=XplatformJson
		public Assignment getJsonToClientAssignment_7_2() { return cJsonToClientAssignment_7_2; }

		//XplatformJson
		public RuleCall getJsonToClientXplatformJsonParserRuleCall_7_2_0() { return cJsonToClientXplatformJsonParserRuleCall_7_2_0; }

		//("server" "expects" jsonToServer=XplatformJson)?
		public Group getGroup_7_3() { return cGroup_7_3; }

		//"server"
		public Keyword getServerKeyword_7_3_0() { return cServerKeyword_7_3_0; }

		//"expects"
		public Keyword getExpectsKeyword_7_3_1() { return cExpectsKeyword_7_3_1; }

		//jsonToServer=XplatformJson
		public Assignment getJsonToServerAssignment_7_3_2() { return cJsonToServerAssignment_7_3_2; }

		//XplatformJson
		public RuleCall getJsonToServerXplatformJsonParserRuleCall_7_3_2_0() { return cJsonToServerXplatformJsonParserRuleCall_7_3_2_0; }
	}

	public class URIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "URI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cANY_OTHERTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cUriParameterAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cUriParameterIDTerminalRuleCall_1_1_0 = (RuleCall)cUriParameterAssignment_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cANY_OTHERTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		
		//URI:
		//	ANY_OTHER+ ("{" uriParameter+=ID "}" ANY_OTHER*)?;
		public ParserRule getRule() { return rule; }

		//ANY_OTHER+ ("{" uriParameter+=ID "}" ANY_OTHER*)?
		public Group getGroup() { return cGroup; }

		//ANY_OTHER+
		public RuleCall getANY_OTHERTerminalRuleCall_0() { return cANY_OTHERTerminalRuleCall_0; }

		//("{" uriParameter+=ID "}" ANY_OTHER*)?
		public Group getGroup_1() { return cGroup_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }

		//uriParameter+=ID
		public Assignment getUriParameterAssignment_1_1() { return cUriParameterAssignment_1_1; }

		//ID
		public RuleCall getUriParameterIDTerminalRuleCall_1_1_0() { return cUriParameterIDTerminalRuleCall_1_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_2() { return cRightCurlyBracketKeyword_1_2; }

		//ANY_OTHER*
		public RuleCall getANY_OTHERTerminalRuleCall_1_3() { return cANY_OTHERTerminalRuleCall_1_3; }
	}

	public class XplatformHeaderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XplatformHeader");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApostropheApostropheApostropheKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHeaderKeyValuesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_2_0 = (RuleCall)cHeaderKeyValuesAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cHeaderKeyValuesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_3_1_0 = (RuleCall)cHeaderKeyValuesAssignment_3_1.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cApostropheApostropheApostropheKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//XplatformHeader:
		//	"\'\'\'" "{" headerKeyValues+=XplatformHeaderKeyValuePair ("," headerKeyValues+=XplatformHeaderKeyValuePair)* ","? "}"
		//	"\'\'\'";
		public ParserRule getRule() { return rule; }

		//"\'\'\'" "{" headerKeyValues+=XplatformHeaderKeyValuePair ("," headerKeyValues+=XplatformHeaderKeyValuePair)* ","? "}"
		//"\'\'\'"
		public Group getGroup() { return cGroup; }

		//"\'\'\'"
		public Keyword getApostropheApostropheApostropheKeyword_0() { return cApostropheApostropheApostropheKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//headerKeyValues+=XplatformHeaderKeyValuePair
		public Assignment getHeaderKeyValuesAssignment_2() { return cHeaderKeyValuesAssignment_2; }

		//XplatformHeaderKeyValuePair
		public RuleCall getHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_2_0() { return cHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_2_0; }

		//("," headerKeyValues+=XplatformHeaderKeyValuePair)*
		public Group getGroup_3() { return cGroup_3; }

		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }

		//headerKeyValues+=XplatformHeaderKeyValuePair
		public Assignment getHeaderKeyValuesAssignment_3_1() { return cHeaderKeyValuesAssignment_3_1; }

		//XplatformHeaderKeyValuePair
		public RuleCall getHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_3_1_0() { return cHeaderKeyValuesXplatformHeaderKeyValuePairParserRuleCall_3_1_0; }

		//","?
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }

		//"\'\'\'"
		public Keyword getApostropheApostropheApostropheKeyword_6() { return cApostropheApostropheApostropheKeyword_6; }
	}

	public class XplatformHeaderKeyValuePairElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XplatformHeaderKeyValuePair");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeySTRINGTerminalRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0_0 = (RuleCall)cValueAssignment_2_0.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cValueXPLATFORM_HEADER_PARAMETERTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		
		//XplatformHeaderKeyValuePair:
		//	key=STRING "=" (value=STRING | value=XPLATFORM_HEADER_PARAMETER);
		public ParserRule getRule() { return rule; }

		//key=STRING "=" (value=STRING | value=XPLATFORM_HEADER_PARAMETER)
		public Group getGroup() { return cGroup; }

		//key=STRING
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }

		//STRING
		public RuleCall getKeySTRINGTerminalRuleCall_0_0() { return cKeySTRINGTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=STRING | value=XPLATFORM_HEADER_PARAMETER
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//value=STRING
		public Assignment getValueAssignment_2_0() { return cValueAssignment_2_0; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0_0() { return cValueSTRINGTerminalRuleCall_2_0_0; }

		//value=XPLATFORM_HEADER_PARAMETER
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }

		//XPLATFORM_HEADER_PARAMETER
		public RuleCall getValueXPLATFORM_HEADER_PARAMETERTerminalRuleCall_2_1_0() { return cValueXPLATFORM_HEADER_PARAMETERTerminalRuleCall_2_1_0; }
	}

	public class XplatformJsonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XplatformJson");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cApostropheApostropheApostropheKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cTypeAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cTypeJsonTypeParserRuleCall_0_1_0 = (RuleCall)cTypeAssignment_0_1.eContents().get(0);
		private final Assignment cMetaTypeAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cMetaTypeJsonMetaTypeParserRuleCall_1_0 = (RuleCall)cMetaTypeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cCompositeAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cCompositeJsonObjectParserRuleCall_2_0_0 = (RuleCall)cCompositeAssignment_2_0.eContents().get(0);
		private final Keyword cApostropheApostropheApostropheKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		
		//XplatformJson:
		//	"\'\'\'" type=JsonType | metaType=JsonMetaType | composite=JsonObject "\'\'\'";
		public ParserRule getRule() { return rule; }

		//"\'\'\'" type=JsonType | metaType=JsonMetaType | composite=JsonObject "\'\'\'"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"\'\'\'" type=JsonType
		public Group getGroup_0() { return cGroup_0; }

		//"\'\'\'"
		public Keyword getApostropheApostropheApostropheKeyword_0_0() { return cApostropheApostropheApostropheKeyword_0_0; }

		//type=JsonType
		public Assignment getTypeAssignment_0_1() { return cTypeAssignment_0_1; }

		//JsonType
		public RuleCall getTypeJsonTypeParserRuleCall_0_1_0() { return cTypeJsonTypeParserRuleCall_0_1_0; }

		//metaType=JsonMetaType
		public Assignment getMetaTypeAssignment_1() { return cMetaTypeAssignment_1; }

		//JsonMetaType
		public RuleCall getMetaTypeJsonMetaTypeParserRuleCall_1_0() { return cMetaTypeJsonMetaTypeParserRuleCall_1_0; }

		//composite=JsonObject "\'\'\'"
		public Group getGroup_2() { return cGroup_2; }

		//composite=JsonObject
		public Assignment getCompositeAssignment_2_0() { return cCompositeAssignment_2_0; }

		//JsonObject
		public RuleCall getCompositeJsonObjectParserRuleCall_2_0_0() { return cCompositeJsonObjectParserRuleCall_2_0_0; }

		//"\'\'\'"
		public Keyword getApostropheApostropheApostropheKeyword_2_1() { return cApostropheApostropheApostropheKeyword_2_1; }
	}

	public class JsonMetaScalarTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonMetaScalarType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cBooleanKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cNumberKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cStringKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//JsonMetaScalarType:
		//	"boolean" | "number" | "string";
		public ParserRule getRule() { return rule; }

		//"boolean" | "number" | "string"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"boolean"
		public Keyword getBooleanKeyword_0() { return cBooleanKeyword_0; }

		//"number"
		public Keyword getNumberKeyword_1() { return cNumberKeyword_1; }

		//"string"
		public Keyword getStringKeyword_2() { return cStringKeyword_2; }
	}

	public class JsonMetaArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonMetaArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMetaTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMetaTypeJsonMetaTypeParserRuleCall_1_0 = (RuleCall)cMetaTypeAssignment_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//JsonMetaArray:
		//	"[" metaType=JsonMetaType "]";
		public ParserRule getRule() { return rule; }

		//"[" metaType=JsonMetaType "]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		//metaType=JsonMetaType
		public Assignment getMetaTypeAssignment_1() { return cMetaTypeAssignment_1; }

		//JsonMetaType
		public RuleCall getMetaTypeJsonMetaTypeParserRuleCall_1_0() { return cMetaTypeJsonMetaTypeParserRuleCall_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
	}

	public class JsonMetaTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonMetaType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cScalarAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cScalarJsonMetaScalarTypeParserRuleCall_0_0 = (RuleCall)cScalarAssignment_0.eContents().get(0);
		private final Assignment cCompositeAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCompositeJsonMetaArrayParserRuleCall_1_0 = (RuleCall)cCompositeAssignment_1.eContents().get(0);
		
		//JsonMetaType:
		//	scalar=JsonMetaScalarType | composite=JsonMetaArray;
		public ParserRule getRule() { return rule; }

		//scalar=JsonMetaScalarType | composite=JsonMetaArray
		public Alternatives getAlternatives() { return cAlternatives; }

		//scalar=JsonMetaScalarType
		public Assignment getScalarAssignment_0() { return cScalarAssignment_0; }

		//JsonMetaScalarType
		public RuleCall getScalarJsonMetaScalarTypeParserRuleCall_0_0() { return cScalarJsonMetaScalarTypeParserRuleCall_0_0; }

		//composite=JsonMetaArray
		public Assignment getCompositeAssignment_1() { return cCompositeAssignment_1; }

		//JsonMetaArray
		public RuleCall getCompositeJsonMetaArrayParserRuleCall_1_0() { return cCompositeJsonMetaArrayParserRuleCall_1_0; }
	}

	public class JsonCompositeTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonCompositeType");
		private final Assignment cCompositeAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCompositeJsonArrayParserRuleCall_0 = (RuleCall)cCompositeAssignment.eContents().get(0);
		
		//JsonCompositeType:
		//	composite=JsonArray;
		public ParserRule getRule() { return rule; }

		//composite=JsonArray
		public Assignment getCompositeAssignment() { return cCompositeAssignment; }

		//JsonArray
		public RuleCall getCompositeJsonArrayParserRuleCall_0() { return cCompositeJsonArrayParserRuleCall_0; }
	}

	public class JsonTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cScalarAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cScalarJsonScalarTypeParserRuleCall_0_0 = (RuleCall)cScalarAssignment_0.eContents().get(0);
		private final Assignment cCompositeAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCompositeJsonCompositeTypeParserRuleCall_1_0 = (RuleCall)cCompositeAssignment_1.eContents().get(0);
		
		//JsonType:
		//	scalar=JsonScalarType | composite=JsonCompositeType;
		public ParserRule getRule() { return rule; }

		//scalar=JsonScalarType | composite=JsonCompositeType
		public Alternatives getAlternatives() { return cAlternatives; }

		//scalar=JsonScalarType
		public Assignment getScalarAssignment_0() { return cScalarAssignment_0; }

		//JsonScalarType
		public RuleCall getScalarJsonScalarTypeParserRuleCall_0_0() { return cScalarJsonScalarTypeParserRuleCall_0_0; }

		//composite=JsonCompositeType
		public Assignment getCompositeAssignment_1() { return cCompositeAssignment_1; }

		//JsonCompositeType
		public RuleCall getCompositeJsonCompositeTypeParserRuleCall_1_0() { return cCompositeJsonCompositeTypeParserRuleCall_1_0; }
	}

	public class JsonScalarTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonScalarType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBoolAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBoolJSON_LITERAL_BOOLEANTerminalRuleCall_0_0 = (RuleCall)cBoolAssignment_0.eContents().get(0);
		private final Assignment cStringAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStringSTRINGTerminalRuleCall_1_0 = (RuleCall)cStringAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cNumberAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_2_0_0 = (RuleCall)cNumberAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cFullStopKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_2_1_1 = (RuleCall)cGroup_2_1.eContents().get(1);
		private final Assignment cNullAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cNullJSON_LITERAL_NULLTerminalRuleCall_3_0 = (RuleCall)cNullAssignment_3.eContents().get(0);
		
		//JsonScalarType:
		//	bool=JSON_LITERAL_BOOLEAN | string=STRING | number=INT ("." INT)? | null=JSON_LITERAL_NULL;
		public ParserRule getRule() { return rule; }

		//bool=JSON_LITERAL_BOOLEAN | string=STRING | number=INT ("." INT)? | null=JSON_LITERAL_NULL
		public Alternatives getAlternatives() { return cAlternatives; }

		//bool=JSON_LITERAL_BOOLEAN
		public Assignment getBoolAssignment_0() { return cBoolAssignment_0; }

		//JSON_LITERAL_BOOLEAN
		public RuleCall getBoolJSON_LITERAL_BOOLEANTerminalRuleCall_0_0() { return cBoolJSON_LITERAL_BOOLEANTerminalRuleCall_0_0; }

		//string=STRING
		public Assignment getStringAssignment_1() { return cStringAssignment_1; }

		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_1_0() { return cStringSTRINGTerminalRuleCall_1_0; }

		//number=INT ("." INT)?
		public Group getGroup_2() { return cGroup_2; }

		//number=INT
		public Assignment getNumberAssignment_2_0() { return cNumberAssignment_2_0; }

		//INT
		public RuleCall getNumberINTTerminalRuleCall_2_0_0() { return cNumberINTTerminalRuleCall_2_0_0; }

		//("." INT)?
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"."
		public Keyword getFullStopKeyword_2_1_0() { return cFullStopKeyword_2_1_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_2_1_1() { return cINTTerminalRuleCall_2_1_1; }

		//null=JSON_LITERAL_NULL
		public Assignment getNullAssignment_3() { return cNullAssignment_3; }

		//JSON_LITERAL_NULL
		public RuleCall getNullJSON_LITERAL_NULLTerminalRuleCall_3_0() { return cNullJSON_LITERAL_NULLTerminalRuleCall_3_0; }
	}

	public class JsonArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonArray");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cElementsAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cElementsJsonScalarTypeParserRuleCall_0_1_0 = (RuleCall)cElementsAssignment_0_1.eContents().get(0);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Keyword cCommaKeyword_0_2_0 = (Keyword)cGroup_0_2.eContents().get(0);
		private final Assignment cElementsAssignment_0_2_1 = (Assignment)cGroup_0_2.eContents().get(1);
		private final RuleCall cElementsJsonScalarTypeParserRuleCall_0_2_1_0 = (RuleCall)cElementsAssignment_0_2_1.eContents().get(0);
		private final Keyword cCommaKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_0_4 = (Keyword)cGroup_0.eContents().get(4);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cCompositesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cCompositesJsonCompositeTypeParserRuleCall_1_1_0 = (RuleCall)cCompositesAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cCompositesAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cCompositesJsonCompositeTypeParserRuleCall_1_2_1_0 = (RuleCall)cCompositesAssignment_1_2_1.eContents().get(0);
		private final Keyword cCommaKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		
		//JsonArray:
		//	"[" elements+=JsonScalarType ("," elements+=JsonScalarType)* ","? "]" | "[" composites+=JsonCompositeType (","
		//	composites+=JsonCompositeType)* ","? "]";
		public ParserRule getRule() { return rule; }

		//"[" elements+=JsonScalarType ("," elements+=JsonScalarType)* ","? "]" | "[" composites+=JsonCompositeType (","
		//composites+=JsonCompositeType)* ","? "]"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"[" elements+=JsonScalarType ("," elements+=JsonScalarType)* ","? "]"
		public Group getGroup_0() { return cGroup_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0_0() { return cLeftSquareBracketKeyword_0_0; }

		//elements+=JsonScalarType
		public Assignment getElementsAssignment_0_1() { return cElementsAssignment_0_1; }

		//JsonScalarType
		public RuleCall getElementsJsonScalarTypeParserRuleCall_0_1_0() { return cElementsJsonScalarTypeParserRuleCall_0_1_0; }

		//("," elements+=JsonScalarType)*
		public Group getGroup_0_2() { return cGroup_0_2; }

		//","
		public Keyword getCommaKeyword_0_2_0() { return cCommaKeyword_0_2_0; }

		//elements+=JsonScalarType
		public Assignment getElementsAssignment_0_2_1() { return cElementsAssignment_0_2_1; }

		//JsonScalarType
		public RuleCall getElementsJsonScalarTypeParserRuleCall_0_2_1_0() { return cElementsJsonScalarTypeParserRuleCall_0_2_1_0; }

		//","?
		public Keyword getCommaKeyword_0_3() { return cCommaKeyword_0_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_0_4() { return cRightSquareBracketKeyword_0_4; }

		//"[" composites+=JsonCompositeType ("," composites+=JsonCompositeType)* ","? "]"
		public Group getGroup_1() { return cGroup_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1_0() { return cLeftSquareBracketKeyword_1_0; }

		//composites+=JsonCompositeType
		public Assignment getCompositesAssignment_1_1() { return cCompositesAssignment_1_1; }

		//JsonCompositeType
		public RuleCall getCompositesJsonCompositeTypeParserRuleCall_1_1_0() { return cCompositesJsonCompositeTypeParserRuleCall_1_1_0; }

		//("," composites+=JsonCompositeType)*
		public Group getGroup_1_2() { return cGroup_1_2; }

		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }

		//composites+=JsonCompositeType
		public Assignment getCompositesAssignment_1_2_1() { return cCompositesAssignment_1_2_1; }

		//JsonCompositeType
		public RuleCall getCompositesJsonCompositeTypeParserRuleCall_1_2_1_0() { return cCompositesJsonCompositeTypeParserRuleCall_1_2_1_0; }

		//","?
		public Keyword getCommaKeyword_1_3() { return cCommaKeyword_1_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_1_4() { return cRightSquareBracketKeyword_1_4; }
	}

	public class JsonObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "JsonObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cKeysAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cKeysSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cKeysAssignment_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cValuesAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cValuesXplatformJsonParserRuleCall_1_2_0 = (RuleCall)cValuesAssignment_1_2.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cKeysAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cKeysSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cKeysAssignment_2_1.eContents().get(0);
		private final Keyword cColonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cValuesAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cValuesXplatformJsonParserRuleCall_2_3_0 = (RuleCall)cValuesAssignment_2_3.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//JsonObject:
		//	"{" (keys+=STRING ":" values+=XplatformJson) ("," keys+=STRING ":" values+=XplatformJson)* ","? "}";
		public ParserRule getRule() { return rule; }

		//"{" (keys+=STRING ":" values+=XplatformJson) ("," keys+=STRING ":" values+=XplatformJson)* ","? "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//keys+=STRING ":" values+=XplatformJson
		public Group getGroup_1() { return cGroup_1; }

		//keys+=STRING
		public Assignment getKeysAssignment_1_0() { return cKeysAssignment_1_0; }

		//STRING
		public RuleCall getKeysSTRINGTerminalRuleCall_1_0_0() { return cKeysSTRINGTerminalRuleCall_1_0_0; }

		//":"
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }

		//values+=XplatformJson
		public Assignment getValuesAssignment_1_2() { return cValuesAssignment_1_2; }

		//XplatformJson
		public RuleCall getValuesXplatformJsonParserRuleCall_1_2_0() { return cValuesXplatformJsonParserRuleCall_1_2_0; }

		//("," keys+=STRING ":" values+=XplatformJson)*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//keys+=STRING
		public Assignment getKeysAssignment_2_1() { return cKeysAssignment_2_1; }

		//STRING
		public RuleCall getKeysSTRINGTerminalRuleCall_2_1_0() { return cKeysSTRINGTerminalRuleCall_2_1_0; }

		//":"
		public Keyword getColonKeyword_2_2() { return cColonKeyword_2_2; }

		//values+=XplatformJson
		public Assignment getValuesAssignment_2_3() { return cValuesAssignment_2_3; }

		//XplatformJson
		public RuleCall getValuesXplatformJsonParserRuleCall_2_3_0() { return cValuesXplatformJsonParserRuleCall_2_3_0; }

		//","?
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class XplatformResourceDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "XplatformResourceDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlatformAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPlatformPlatformParserRuleCall_0_0 = (RuleCall)cPlatformAssignment_0.eContents().get(0);
		private final Assignment cTypesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypesTypeParserRuleCall_1_0 = (RuleCall)cTypesAssignment_1.eContents().get(0);
		
		/// **
		// * 
		// * Xplatform resource generator
		// * 
		// * / XplatformResourceDefinition:
		//	platform=Platform types+=Type+;
		public ParserRule getRule() { return rule; }

		//platform=Platform types+=Type+
		public Group getGroup() { return cGroup; }

		//platform=Platform
		public Assignment getPlatformAssignment_0() { return cPlatformAssignment_0; }

		//Platform
		public RuleCall getPlatformPlatformParserRuleCall_0_0() { return cPlatformPlatformParserRuleCall_0_0; }

		//types+=Type+
		public Assignment getTypesAssignment_1() { return cTypesAssignment_1; }

		//Type
		public RuleCall getTypesTypeParserRuleCall_1_0() { return cTypesTypeParserRuleCall_1_0; }
	}

	public class PlatformElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Platform");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlatformKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlatformsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPlatformsSTRINGTerminalRuleCall_2_0 = (RuleCall)cPlatformsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Platform:
		//	"platform" "{" platforms+=STRING+ "}";
		public ParserRule getRule() { return rule; }

		//"platform" "{" platforms+=STRING+ "}"
		public Group getGroup() { return cGroup; }

		//"platform"
		public Keyword getPlatformKeyword_0() { return cPlatformKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//platforms+=STRING+
		public Assignment getPlatformsAssignment_2() { return cPlatformsAssignment_2; }

		//STRING
		public RuleCall getPlatformsSTRINGTerminalRuleCall_2_0() { return cPlatformsSTRINGTerminalRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMapInstanceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEnumInstanceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//	MapInstance | EnumInstance;
		public ParserRule getRule() { return rule; }

		//MapInstance | EnumInstance
		public Alternatives getAlternatives() { return cAlternatives; }

		//MapInstance
		public RuleCall getMapInstanceParserRuleCall_0() { return cMapInstanceParserRuleCall_0; }

		//EnumInstance
		public RuleCall getEnumInstanceParserRuleCall_1() { return cEnumInstanceParserRuleCall_1; }
	}

	public class EnumInstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EnumInstance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEnumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEnumNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEnumNameIDTerminalRuleCall_1_0 = (RuleCall)cEnumNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValuesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValuesIDTerminalRuleCall_3_0 = (RuleCall)cValuesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValuesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValuesIDTerminalRuleCall_4_1_0 = (RuleCall)cValuesAssignment_4_1.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EnumInstance:
		//	"enum" enumName=ID "{" values+=ID ("," values+=ID)* ","? "}";
		public ParserRule getRule() { return rule; }

		//"enum" enumName=ID "{" values+=ID ("," values+=ID)* ","? "}"
		public Group getGroup() { return cGroup; }

		//"enum"
		public Keyword getEnumKeyword_0() { return cEnumKeyword_0; }

		//enumName=ID
		public Assignment getEnumNameAssignment_1() { return cEnumNameAssignment_1; }

		//ID
		public RuleCall getEnumNameIDTerminalRuleCall_1_0() { return cEnumNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//values+=ID
		public Assignment getValuesAssignment_3() { return cValuesAssignment_3; }

		//ID
		public RuleCall getValuesIDTerminalRuleCall_3_0() { return cValuesIDTerminalRuleCall_3_0; }

		//("," values+=ID)*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//values+=ID
		public Assignment getValuesAssignment_4_1() { return cValuesAssignment_4_1; }

		//ID
		public RuleCall getValuesIDTerminalRuleCall_4_1_0() { return cValuesIDTerminalRuleCall_4_1_0; }

		//","?
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class MapInstanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MapInstance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMapKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMapNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMapNameIDTerminalRuleCall_1_0 = (RuleCall)cMapNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValuesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValuesIDTerminalRuleCall_3_0 = (RuleCall)cValuesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValuesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValuesIDTerminalRuleCall_4_1_0 = (RuleCall)cValuesAssignment_4_1.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//MapInstance:
		//	"map" mapName=ID "{" values+=ID ("," values+=ID)* ","? // you must have at least one map
		//	"}";
		public ParserRule getRule() { return rule; }

		//"map" mapName=ID "{" values+=ID ("," values+=ID)* ","? // you must have at least one map
		//"}"
		public Group getGroup() { return cGroup; }

		//"map"
		public Keyword getMapKeyword_0() { return cMapKeyword_0; }

		//mapName=ID
		public Assignment getMapNameAssignment_1() { return cMapNameAssignment_1; }

		//ID
		public RuleCall getMapNameIDTerminalRuleCall_1_0() { return cMapNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//values+=ID
		public Assignment getValuesAssignment_3() { return cValuesAssignment_3; }

		//ID
		public RuleCall getValuesIDTerminalRuleCall_3_0() { return cValuesIDTerminalRuleCall_3_0; }

		//("," values+=ID)*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//values+=ID
		public Assignment getValuesAssignment_4_1() { return cValuesAssignment_4_1; }

		//ID
		public RuleCall getValuesIDTerminalRuleCall_4_1_0() { return cValuesIDTerminalRuleCall_4_1_0; }

		//","?
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }

		//// you must have at least one map
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class StringListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValuesSTRINGTerminalRuleCall_1_0 = (RuleCall)cValuesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cValuesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValuesSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cValuesAssignment_2_1.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//StringList:
		//	"[" values+=STRING ("," values+=STRING)* ","? "]";
		public ParserRule getRule() { return rule; }

		//"[" values+=STRING ("," values+=STRING)* ","? "]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		//values+=STRING
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }

		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_1_0() { return cValuesSTRINGTerminalRuleCall_1_0; }

		//("," values+=STRING)*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//values+=STRING
		public Assignment getValuesAssignment_2_1() { return cValuesAssignment_2_1; }

		//STRING
		public RuleCall getValuesSTRINGTerminalRuleCall_2_1_0() { return cValuesSTRINGTerminalRuleCall_2_1_0; }

		//","?
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}

	public class KeyValuePairElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "KeyValuePair");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKeyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKeyIDTerminalRuleCall_0_0 = (RuleCall)cKeyAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueTypeParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//KeyValuePair:
		//	key=ID ":" value=ValueType;
		public ParserRule getRule() { return rule; }

		//key=ID ":" value=ValueType
		public Group getGroup() { return cGroup; }

		//key=ID
		public Assignment getKeyAssignment_0() { return cKeyAssignment_0; }

		//ID
		public RuleCall getKeyIDTerminalRuleCall_0_0() { return cKeyIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//value=ValueType
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//ValueType
		public RuleCall getValueValueTypeParserRuleCall_2_0() { return cValueValueTypeParserRuleCall_2_0; }
	}

	public class ValueTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ValueType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cStringAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cStringSTRINGTerminalRuleCall_0_0 = (RuleCall)cStringAssignment_0.eContents().get(0);
		private final Assignment cStringListAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStringListStringListParserRuleCall_1_0 = (RuleCall)cStringListAssignment_1.eContents().get(0);
		
		//ValueType:
		//	string=STRING | stringList=StringList;
		public ParserRule getRule() { return rule; }

		//string=STRING | stringList=StringList
		public Alternatives getAlternatives() { return cAlternatives; }

		//string=STRING
		public Assignment getStringAssignment_0() { return cStringAssignment_0; }

		//STRING
		public RuleCall getStringSTRINGTerminalRuleCall_0_0() { return cStringSTRINGTerminalRuleCall_0_0; }

		//stringList=StringList
		public Assignment getStringListAssignment_1() { return cStringListAssignment_1; }

		//StringList
		public RuleCall getStringListStringListParserRuleCall_1_0() { return cStringListStringListParserRuleCall_1_0; }
	}
	
	
	private XplatformElements pXplatform;
	private XplatformCallDefinitionElements pXplatformCallDefinition;
	private URIElements pURI;
	private XplatformHeaderElements pXplatformHeader;
	private XplatformHeaderKeyValuePairElements pXplatformHeaderKeyValuePair;
	private TerminalRule tXPLATFORM_HEADER_PARAMETER;
	private TerminalRule tRESTFUL_METHODS;
	private XplatformJsonElements pXplatformJson;
	private TerminalRule tJSON_LITERAL_NULL;
	private TerminalRule tJSON_LITERAL_BOOLEAN;
	private JsonMetaScalarTypeElements pJsonMetaScalarType;
	private JsonMetaArrayElements pJsonMetaArray;
	private JsonMetaTypeElements pJsonMetaType;
	private JsonCompositeTypeElements pJsonCompositeType;
	private JsonTypeElements pJsonType;
	private JsonScalarTypeElements pJsonScalarType;
	private JsonArrayElements pJsonArray;
	private JsonObjectElements pJsonObject;
	private XplatformResourceDefinitionElements pXplatformResourceDefinition;
	private PlatformElements pPlatform;
	private TypeElements pType;
	private EnumInstanceElements pEnumInstance;
	private MapInstanceElements pMapInstance;
	private StringListElements pStringList;
	private KeyValuePairElements pKeyValuePair;
	private ValueTypeElements pValueType;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public XplatformGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nl.sison.Xplatform".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	/// **
	// * 
	// * Xplatform http call generator parser
	// * 
	// * / Xplatform:
	//	(resources+=XplatformResourceDefinition | calls+=XplatformCallDefinition)+;
	public XplatformElements getXplatformAccess() {
		return (pXplatform != null) ? pXplatform : (pXplatform = new XplatformElements());
	}
	
	public ParserRule getXplatformRule() {
		return getXplatformAccess().getRule();
	}

	//XplatformCallDefinition:
	//	"call" name=ID ":" method=RESTFUL_METHODS "from" uri=URI ("with" "headers" "from" "request"
	//	requestHeaders=XplatformHeader ("and" "response" responseHeaders=XplatformHeader)?)? ("client" "expects"
	//	jsonToClient=XplatformJson ("server" "expects" jsonToServer=XplatformJson)?)?;
	public XplatformCallDefinitionElements getXplatformCallDefinitionAccess() {
		return (pXplatformCallDefinition != null) ? pXplatformCallDefinition : (pXplatformCallDefinition = new XplatformCallDefinitionElements());
	}
	
	public ParserRule getXplatformCallDefinitionRule() {
		return getXplatformCallDefinitionAccess().getRule();
	}

	//URI:
	//	ANY_OTHER+ ("{" uriParameter+=ID "}" ANY_OTHER*)?;
	public URIElements getURIAccess() {
		return (pURI != null) ? pURI : (pURI = new URIElements());
	}
	
	public ParserRule getURIRule() {
		return getURIAccess().getRule();
	}

	//XplatformHeader:
	//	"\'\'\'" "{" headerKeyValues+=XplatformHeaderKeyValuePair ("," headerKeyValues+=XplatformHeaderKeyValuePair)* ","? "}"
	//	"\'\'\'";
	public XplatformHeaderElements getXplatformHeaderAccess() {
		return (pXplatformHeader != null) ? pXplatformHeader : (pXplatformHeader = new XplatformHeaderElements());
	}
	
	public ParserRule getXplatformHeaderRule() {
		return getXplatformHeaderAccess().getRule();
	}

	//XplatformHeaderKeyValuePair:
	//	key=STRING "=" (value=STRING | value=XPLATFORM_HEADER_PARAMETER);
	public XplatformHeaderKeyValuePairElements getXplatformHeaderKeyValuePairAccess() {
		return (pXplatformHeaderKeyValuePair != null) ? pXplatformHeaderKeyValuePair : (pXplatformHeaderKeyValuePair = new XplatformHeaderKeyValuePairElements());
	}
	
	public ParserRule getXplatformHeaderKeyValuePairRule() {
		return getXplatformHeaderKeyValuePairAccess().getRule();
	}

	//terminal XPLATFORM_HEADER_PARAMETER:
	//	"{" ID "}";
	public TerminalRule getXPLATFORM_HEADER_PARAMETERRule() {
		return (tXPLATFORM_HEADER_PARAMETER != null) ? tXPLATFORM_HEADER_PARAMETER : (tXPLATFORM_HEADER_PARAMETER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "XPLATFORM_HEADER_PARAMETER"));
	} 

	//terminal RESTFUL_METHODS:
	//	"PUT" | "POST" | "GET" | // TODO HEAD will be automagically generated as well, a body-less response
	//	"DELETE";
	public TerminalRule getRESTFUL_METHODSRule() {
		return (tRESTFUL_METHODS != null) ? tRESTFUL_METHODS : (tRESTFUL_METHODS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RESTFUL_METHODS"));
	} 

	//XplatformJson:
	//	"\'\'\'" type=JsonType | metaType=JsonMetaType | composite=JsonObject "\'\'\'";
	public XplatformJsonElements getXplatformJsonAccess() {
		return (pXplatformJson != null) ? pXplatformJson : (pXplatformJson = new XplatformJsonElements());
	}
	
	public ParserRule getXplatformJsonRule() {
		return getXplatformJsonAccess().getRule();
	}

	//terminal JSON_LITERAL_NULL:
	//	"null";
	public TerminalRule getJSON_LITERAL_NULLRule() {
		return (tJSON_LITERAL_NULL != null) ? tJSON_LITERAL_NULL : (tJSON_LITERAL_NULL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JSON_LITERAL_NULL"));
	} 

	//terminal JSON_LITERAL_BOOLEAN:
	//	"true" | "false";
	public TerminalRule getJSON_LITERAL_BOOLEANRule() {
		return (tJSON_LITERAL_BOOLEAN != null) ? tJSON_LITERAL_BOOLEAN : (tJSON_LITERAL_BOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JSON_LITERAL_BOOLEAN"));
	} 

	//JsonMetaScalarType:
	//	"boolean" | "number" | "string";
	public JsonMetaScalarTypeElements getJsonMetaScalarTypeAccess() {
		return (pJsonMetaScalarType != null) ? pJsonMetaScalarType : (pJsonMetaScalarType = new JsonMetaScalarTypeElements());
	}
	
	public ParserRule getJsonMetaScalarTypeRule() {
		return getJsonMetaScalarTypeAccess().getRule();
	}

	//JsonMetaArray:
	//	"[" metaType=JsonMetaType "]";
	public JsonMetaArrayElements getJsonMetaArrayAccess() {
		return (pJsonMetaArray != null) ? pJsonMetaArray : (pJsonMetaArray = new JsonMetaArrayElements());
	}
	
	public ParserRule getJsonMetaArrayRule() {
		return getJsonMetaArrayAccess().getRule();
	}

	//JsonMetaType:
	//	scalar=JsonMetaScalarType | composite=JsonMetaArray;
	public JsonMetaTypeElements getJsonMetaTypeAccess() {
		return (pJsonMetaType != null) ? pJsonMetaType : (pJsonMetaType = new JsonMetaTypeElements());
	}
	
	public ParserRule getJsonMetaTypeRule() {
		return getJsonMetaTypeAccess().getRule();
	}

	//JsonCompositeType:
	//	composite=JsonArray;
	public JsonCompositeTypeElements getJsonCompositeTypeAccess() {
		return (pJsonCompositeType != null) ? pJsonCompositeType : (pJsonCompositeType = new JsonCompositeTypeElements());
	}
	
	public ParserRule getJsonCompositeTypeRule() {
		return getJsonCompositeTypeAccess().getRule();
	}

	//JsonType:
	//	scalar=JsonScalarType | composite=JsonCompositeType;
	public JsonTypeElements getJsonTypeAccess() {
		return (pJsonType != null) ? pJsonType : (pJsonType = new JsonTypeElements());
	}
	
	public ParserRule getJsonTypeRule() {
		return getJsonTypeAccess().getRule();
	}

	//JsonScalarType:
	//	bool=JSON_LITERAL_BOOLEAN | string=STRING | number=INT ("." INT)? | null=JSON_LITERAL_NULL;
	public JsonScalarTypeElements getJsonScalarTypeAccess() {
		return (pJsonScalarType != null) ? pJsonScalarType : (pJsonScalarType = new JsonScalarTypeElements());
	}
	
	public ParserRule getJsonScalarTypeRule() {
		return getJsonScalarTypeAccess().getRule();
	}

	//JsonArray:
	//	"[" elements+=JsonScalarType ("," elements+=JsonScalarType)* ","? "]" | "[" composites+=JsonCompositeType (","
	//	composites+=JsonCompositeType)* ","? "]";
	public JsonArrayElements getJsonArrayAccess() {
		return (pJsonArray != null) ? pJsonArray : (pJsonArray = new JsonArrayElements());
	}
	
	public ParserRule getJsonArrayRule() {
		return getJsonArrayAccess().getRule();
	}

	//JsonObject:
	//	"{" (keys+=STRING ":" values+=XplatformJson) ("," keys+=STRING ":" values+=XplatformJson)* ","? "}";
	public JsonObjectElements getJsonObjectAccess() {
		return (pJsonObject != null) ? pJsonObject : (pJsonObject = new JsonObjectElements());
	}
	
	public ParserRule getJsonObjectRule() {
		return getJsonObjectAccess().getRule();
	}

	/// **
	// * 
	// * Xplatform resource generator
	// * 
	// * / XplatformResourceDefinition:
	//	platform=Platform types+=Type+;
	public XplatformResourceDefinitionElements getXplatformResourceDefinitionAccess() {
		return (pXplatformResourceDefinition != null) ? pXplatformResourceDefinition : (pXplatformResourceDefinition = new XplatformResourceDefinitionElements());
	}
	
	public ParserRule getXplatformResourceDefinitionRule() {
		return getXplatformResourceDefinitionAccess().getRule();
	}

	//Platform:
	//	"platform" "{" platforms+=STRING+ "}";
	public PlatformElements getPlatformAccess() {
		return (pPlatform != null) ? pPlatform : (pPlatform = new PlatformElements());
	}
	
	public ParserRule getPlatformRule() {
		return getPlatformAccess().getRule();
	}

	//Type:
	//	MapInstance | EnumInstance;
	public TypeElements getTypeAccess() {
		return (pType != null) ? pType : (pType = new TypeElements());
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//EnumInstance:
	//	"enum" enumName=ID "{" values+=ID ("," values+=ID)* ","? "}";
	public EnumInstanceElements getEnumInstanceAccess() {
		return (pEnumInstance != null) ? pEnumInstance : (pEnumInstance = new EnumInstanceElements());
	}
	
	public ParserRule getEnumInstanceRule() {
		return getEnumInstanceAccess().getRule();
	}

	//MapInstance:
	//	"map" mapName=ID "{" values+=ID ("," values+=ID)* ","? // you must have at least one map
	//	"}";
	public MapInstanceElements getMapInstanceAccess() {
		return (pMapInstance != null) ? pMapInstance : (pMapInstance = new MapInstanceElements());
	}
	
	public ParserRule getMapInstanceRule() {
		return getMapInstanceAccess().getRule();
	}

	//StringList:
	//	"[" values+=STRING ("," values+=STRING)* ","? "]";
	public StringListElements getStringListAccess() {
		return (pStringList != null) ? pStringList : (pStringList = new StringListElements());
	}
	
	public ParserRule getStringListRule() {
		return getStringListAccess().getRule();
	}

	//KeyValuePair:
	//	key=ID ":" value=ValueType;
	public KeyValuePairElements getKeyValuePairAccess() {
		return (pKeyValuePair != null) ? pKeyValuePair : (pKeyValuePair = new KeyValuePairElements());
	}
	
	public ParserRule getKeyValuePairRule() {
		return getKeyValuePairAccess().getRule();
	}

	//ValueType:
	//	string=STRING | stringList=StringList;
	public ValueTypeElements getValueTypeAccess() {
		return (pValueType != null) ? pValueType : (pValueType = new ValueTypeElements());
	}
	
	public ParserRule getValueTypeRule() {
		return getValueTypeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
