package nl.sison.dsl.generator;

import com.google.common.collect.Iterators;
import java.util.Iterator;
import java.util.List;
import nl.sison.dsl.mobgen.MobgenCallDefinition;
import nl.sison.dsl.mobgen.URI;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@SuppressWarnings("all")
public class AndroidCallRequestGenerator implements IGenerator {
  public void doGenerate(final Resource input, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = input.getAllContents();
    final Iterator<MobgenCallDefinition> callDefinitions = Iterators.<MobgenCallDefinition>filter(_allContents, MobgenCallDefinition.class);
    final Procedure1<MobgenCallDefinition> _function = new Procedure1<MobgenCallDefinition>() {
        public void apply(final MobgenCallDefinition d) {
          AndroidCallRequestGenerator.this.androidCreateJavaFiles(d, fsa);
        }
      };
    IteratorExtensions.<MobgenCallDefinition>forEach(callDefinitions, _function);
  }
  
  public void androidCreateJavaFiles(final MobgenCallDefinition callDefinition, final IFileSystemAccess fsa) {
    final String name = callDefinition.getName();
    String _method = callDefinition.getMethod();
    final String method = this.capitalizeFirstLetter(_method);
    final URI uri = callDefinition.getUri();
    final EList<String> urlParams = uri.getParameters();
    StringBuffer _stringBuffer = new StringBuffer();
    final StringBuffer stringBuffer = _stringBuffer;
    EList<String> _stringPrefix = uri.getStringPrefix();
    String _string = _stringPrefix.toString();
    CharSequence _setPackage = this.setPackage(_string);
    stringBuffer.append(_setPackage);
    String _capitalizeFirstLetter = this.capitalizeFirstLetter(name);
    String _plus = (_capitalizeFirstLetter + "Loader.java");
    String _string_1 = stringBuffer.toString();
    fsa.generateFile(_plus, _string_1);
  }
  
  public String capitalizeFirstLetter(final String s) {
    String _substring = s.substring(0, 1);
    String _upperCase = _substring.toUpperCase();
    String _substring_1 = s.substring(1);
    String _lowerCase = _substring_1.toLowerCase();
    return (_upperCase + _lowerCase);
  }
  
  /**
   * // TODO assemble imports from generated file(s)
   * def setImports(ArrayList<String> list)
   * {
   * return list.fold("") [result, s | result + "\nimport " + s]
   * }
   */
  public CharSequence wrapAsLoader(final CharSequence className, final CharSequence returnType, final CharSequence method, final CharSequence requestBody, final CharSequence jsonParserToParcelable, final CharSequence serverBoundPayload) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import android.content.AsyncTaskLoader;");
    _builder.newLine();
    _builder.append("import android.content.Context;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.Map; // see http call");
    _builder.newLine();
    _builder.newLine();
    _builder.append("// inspired by http://blog.gunawan.me/2011/10/android-asynctaskloader-exception.html");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className, "");
    _builder.append("Loader extends AsyncTaskLoader<");
    _builder.append(returnType, "");
    _builder.append(">");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append(returnType, "	");
    _builder.append(" result;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(className, "	");
    _builder.append("Loader(Context context) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("super(context);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(className, "	");
    _builder.append("Loader(Context context, String param) { // TODO params");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this(context);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// this.param = param;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// Load the data asynchronously");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(returnType, "	");
    _builder.append(" loadInBackground() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("try");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(className, "			");
    _builder.append("HttpRequest.setParameters(TODO); // TODO");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append(className, "			");
    _builder.append("HttpRequest.do");
    _builder.append(method, "			");
    _builder.append("Request();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return ");
    _builder.append(className, "			");
    _builder.append("HttpRequest.getResult();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("* if this invoked http request throws an exception");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("* TODO Let the exception object come through the \'result\' object");
    _builder.newLine();
    _builder.append("\t\t\t ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}catch (Exception e)");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return ");
    _builder.append(returnType, "			");
    _builder.append("(e); // TODO define this");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void deliverResult(");
    _builder.append(returnType, "	");
    _builder.append(" data) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("if (isReset()) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("// some data came in while the loader is stopped");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.result = data;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.deliverResult(data);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected void onStartLoading() {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("if (result != null) { // This determines the difference between initLoader and restartLoader ");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("deliverResult(result);");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("if (takeContentChanged() || result == null) {");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("forceLoad();");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected void onStopLoading() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("cancelLoad();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected void onReset() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.onReset();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("cancelLoad();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("result = null;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private class ");
    _builder.append(className, "	");
    _builder.append("HttpRequest");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("public final static ");
    _builder.append(className, "		");
    _builder.append("HttpRequest INSTANCE = new ");
    _builder.append(className, "		");
    _builder.append("HttpRequest(); ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("private ");
    _builder.append(className, "		");
    _builder.append("HttpRequest() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("disableConnectionReuseIfNecessary();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("private static ");
    _builder.append(returnType, "		");
    _builder.append(" result = null; ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("public static ");
    _builder.append(returnType, "		");
    _builder.append(" getResult() { return result; }");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO feed parameters to urlParams, headerParams, readStream and writeStream, through outer class, it\'s unnecessary to declare private members twice");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("public do");
    _builder.append(method, "		");
    _builder.append("Request()");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(requestBody, "			");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("* readStream parses a JSON then assigns a Parcelable to this.result");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("private void readStream(BufferedInputStream in)");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(jsonParserToParcelable, "			");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    {
      String _string = method.toString();
      boolean _startsWith = _string.startsWith("P");
      if (_startsWith) {
        _builder.append("\t\t");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append(" ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append(" ");
        _builder.append("* Convert parameters to JSON conforming to the server\'s expection of the call");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append(" ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append(" ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("private void writeStream(BufferedOutputStream out)");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("{");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append(serverBoundPayload, "			");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("\t\t");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("* TODO consider removing this remnant of the past, remove if it pre-dates AsyncTaskLoader(?).");
    _builder.newLine();
    _builder.append("\t\t ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("private void disableConnectionReuseIfNecessary() {");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("// HTTP connection reuse which was buggy pre-froyo");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("if (Integer.parseInt(Build.VERSION.SDK) < Build.VERSION_CODES.FROYO) {");
    _builder.newLine();
    _builder.append("\t\t        ");
    _builder.append("System.setProperty(\"http.keepAlive\", \"false\");");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  /**
   * We got, boolean (faked Integer), Integers, Serializables, Parcelables, String...
   */
  public CharSequence createParcelable(final CharSequence returnType, final List<String> parameterNames, final List<String> parameterTypes) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class ");
    _builder.append(returnType, "");
    _builder.append(" extends Parcelable");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected String lastComment;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Integer messageCount;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("protected Date createdAt;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Conversation(Parcel in) {");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("readFromParcel(in);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void writeToParcel(Parcel out, int flags) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("out.writeString(lastComment);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("out.writeInt(messageCount);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("out.writeSerializable(createdAt);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private void readFromParcel(Parcel in) {  ");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("lastComment = in.readString();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("messageCount = in.readInt();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("createdAt = (Date) in.readSerializable();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("public ");
    _builder.append(returnType, "        ");
    _builder.append(" createFromParcel(Parcel in) {");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("return new ");
    _builder.append(returnType, "            ");
    _builder.append("(in);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("public ");
    _builder.append(returnType, "        ");
    _builder.append("[] newArray(int size) {");
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("return new ");
    _builder.append(returnType, "            ");
    _builder.append(" [size];");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public int describeContents() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return 0;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence setPackage(final String url) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package nl.sison.dsl.mobgen.http");
    {
      boolean _startsWith = url.startsWith("https://");
      if (_startsWith) {
        _builder.append("\"s\"");
      }
    }
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    return _builder;
  }
  
  public String isTransportLayerSecured(final String url) {
    String _xifexpression = null;
    boolean _startsWith = url.startsWith("https://");
    if (_startsWith) {
      _xifexpression = "HttpsURLConnection";
    } else {
      _xifexpression = "HttpURLConnection";
    }
    return _xifexpression;
  }
  
  public CharSequence setRequestProperty(final CharSequence key, final CharSequence parameterOrLiteral) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("urlConnection.setRequestProperty(\"");
    _builder.append(key, "");
    _builder.append("\", ");
    _builder.append(parameterOrLiteral, "");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence generateExceptionHandlerLoggingAndThrow(final CharSequence exceptionType) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("}catch(");
    _builder.append(exceptionType, "");
    _builder.append(" e) // TODO do error handling on the UI thread? Toast#show or pass it on via the result object thru the Loader?");
    _builder.newLineIfNotEmpty();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (BuildConfig.DEBUG)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Log.d(\"MOBGEN\", \"...\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("throw e;");
    _builder.newLine();
    return _builder;
  }
  
  /**
   * TODO must escape nasty symbols in the header injection part using URLEncoder#encode/?
   */
  public CharSequence httpRequestBuilder(final CharSequence url, final CharSequence method, final CharSequence requestPropertyKeyValuePairs) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("URL url = new URL(\"");
    _builder.append(url, "");
    _builder.append("\"); // URLEncoder.encode(...) ");
    _builder.newLineIfNotEmpty();
    String _string = url.toString();
    String _isTransportLayerSecured = this.isTransportLayerSecured(_string);
    _builder.append(_isTransportLayerSecured, "");
    _builder.append(" urlConnection = new ");
    String _string_1 = url.toString();
    String _isTransportLayerSecured_1 = this.isTransportLayerSecured(_string_1);
    _builder.append(_isTransportLayerSecured_1, "");
    _builder.append("(url);");
    _builder.newLineIfNotEmpty();
    _builder.append(requestPropertyKeyValuePairs, "");
    _builder.newLineIfNotEmpty();
    _builder.append("urlConnection.setMethod(\"");
    String _string_2 = method.toString();
    String _upperCase = _string_2.toUpperCase();
    _builder.append(_upperCase, "");
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("urlConnection.setConnectionTimeout(10000); // 10 seconds, default over configuration principle");
    _builder.newLine();
    _builder.append("urlConnection.setReadTimeout(10000); // 10 seconds");
    _builder.newLine();
    _builder.append("urlConnection.setDoInput(true)");
    _builder.newLine();
    {
      String _string_3 = method.toString();
      boolean _startsWith = _string_3.startsWith("P");
      if (_startsWith) {
        _builder.append(" // if POST or PUT");
        _builder.newLineIfNotEmpty();
        _builder.append("urlConnection.setDoOutput(true);");
        _builder.newLine();
      } else {
        _builder.append("urlConnection.setDoOutput(false);");
        _builder.newLine();
      }
    }
    _builder.append("InputStream in = null;");
    _builder.newLine();
    {
      String _string_4 = method.toString();
      boolean _startsWith_1 = _string_4.startsWith("P");
      if (_startsWith_1) {
        _builder.append(" // if POST or PUT");
        _builder.newLineIfNotEmpty();
        _builder.append("OutputStream out = null;");
        _builder.newLine();
      }
    }
    _builder.append("try");
    _builder.newLine();
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("urlConnection.connect();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if (!url.getHost().equals(urlConnection.getURL().getHost())) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("throw new IllegalStateException(\"You were probably redirected to a sign-on.\"); // TODO Let the Activity/Fragment handle this...");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO fire up a browser to sign-on. sharedIntent.");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("in = new BufferedInputStream(urlConnection.getInputStream());");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("readStream(in);");
    _builder.newLine();
    _builder.append("\t");
    {
      String _string_5 = method.toString();
      boolean _startsWith_2 = _string_5.startsWith("P");
      if (_startsWith_2) {
        _builder.append(" // if POST or PUT");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("out = new BufferedOutputStream(urlConnection.getOutputStream());");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("writeStream(out);");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("if (BuildConfig.DEBUG)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Map<String, List<String>> responseHeaders = urlConnection.getHeaderFields(); // do import statement");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (Map.Entry<String, List> entry : map.entrySet())");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("StringBuffer stringList = new StringBuffer();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("for (String s : entry.getValue())");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("stringList.append(s);\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t    ");
    _builder.append("Log.e(\"MOBGEN\", String.format(\"key = %s / value = %s\", entry.getKey(), stringList.toString()));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    CharSequence _generateExceptionHandlerLoggingAndThrow = this.generateExceptionHandlerLoggingAndThrow("IOException");
    _builder.append(_generateExceptionHandlerLoggingAndThrow, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateExceptionHandlerLoggingAndThrow_1 = this.generateExceptionHandlerLoggingAndThrow("UnknownServiceException");
    _builder.append(_generateExceptionHandlerLoggingAndThrow_1, "");
    _builder.newLineIfNotEmpty();
    CharSequence _generateExceptionHandlerLoggingAndThrow_2 = this.generateExceptionHandlerLoggingAndThrow("IllegalAccessError");
    _builder.append(_generateExceptionHandlerLoggingAndThrow_2, "");
    _builder.newLineIfNotEmpty();
    _builder.append("}finally {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("try");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (urlConnection != null)");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("urlConnection.disconnect(); // TODO handle this exception separately");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (in != null)");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("in.close(); // TODO handle this exception separately");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    {
      String _string_6 = method.toString();
      boolean _startsWith_3 = _string_6.startsWith("P");
      if (_startsWith_3) {
        _builder.append(" // if POST or PUT");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("if (out != null)");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("{");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("out.close(); // TODO handle this exception separately");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    CharSequence _generateExceptionHandlerLoggingAndThrow_3 = this.generateExceptionHandlerLoggingAndThrow("IOException");
    _builder.append(_generateExceptionHandlerLoggingAndThrow_3, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
