/*
* generated by Xtext
*/
package nl.sison.dsl.mobgen.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import nl.sison.dsl.mobgen.services.RestfulGrammarAccess;

public class RestfulParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RestfulGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected nl.sison.dsl.mobgen.parser.antlr.internal.InternalRestfulParser createParser(XtextTokenStream stream) {
		return new nl.sison.dsl.mobgen.parser.antlr.internal.InternalRestfulParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Mobgen";
	}
	
	public RestfulGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RestfulGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
