/*
* generated by Xtext
*/
package nl.sison.dsl.mobgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JsonGenStandaloneSetup extends JsonGenStandaloneSetupGenerated{

	public static void doSetup() {
		new JsonGenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

