/*
* generated by Xtext
*/
package nl.sison.dsl.ui.contentassist;

import nl.sison.dsl.ui.contentassist.AbstractMobgenProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MobgenProposalProvider extends AbstractMobgenProposalProvider {

}
