/*
* generated by Xtext
*/
package nl.sison.dsl.mobgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RestfulStandaloneSetup extends RestfulStandaloneSetupGenerated{

	public static void doSetup() {
		new RestfulStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

