/*
 * generated by Xtext
 */
package nl.sison.dsl.mobgen.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import nl.sison.dsl.mobgen.ui.internal.JsonGenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JsonGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JsonGenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JsonGenActivator.getInstance().getInjector(JsonGenActivator.NL_SISON_DSL_MOBGEN_JSONGEN);
	}
	
}
