/**
 * generated by Xtext
 */
package nl.sison.dsl.mobgen.generator;

import nl.sison.dsl.mobgen.generator.AndroidHttpRequestGenerator;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;

@SuppressWarnings("all")
public class RestfulGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    AndroidHttpRequestGenerator _androidHttpRequestGenerator = new AndroidHttpRequestGenerator();
    _androidHttpRequestGenerator.doGenerate(resource, fsa);
  }
}
